---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kyverno.yaml

configMapGenerator:
  - name: flux-kyverno-config
    files:
      - values.yaml=kyverno-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: admission

configurations:
  - kustomizeconfig.yaml
