apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  targetNamespace: dragonfly-operator-system
  interval: 1h
  chart:
    spec:
      chart: dragonfly-operator
      version: "v1.4.0"
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
