apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-deprecated-apis
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-v1-25-removals
      match:
        any:
          - resources:
              kinds:
                - batch/*/CronJob
                - discovery.k8s.io/*/EndpointSlice
                - events.k8s.io/*/Event
                - policy/*/PodDisruptionBudget
                - node.k8s.io/*/RuntimeClass
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
          - key: "{{request.object.apiVersion}}"
            operator: AnyIn
            value:
              - batch/v1beta1
              - discovery.k8s.io/v1beta1
              - events.k8s.io/v1beta1
              - policy/v1beta1
              - node.k8s.io/v1beta1
      validate:
        message: >-
          {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.25.
          See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        deny: {}
    - name: validate-v1-26-removals
      match:
        any:
          - resources:
              kinds:
                - flowcontrol.apiserver.k8s.io/*/FlowSchema
                - flowcontrol.apiserver.k8s.io/*/PriorityLevelConfiguration
                - autoscaling/*/HorizontalPodAutoscaler
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
          - key: "{{request.object.apiVersion}}"
            operator: AnyIn
            value:
              - flowcontrol.apiserver.k8s.io/v1beta1
              - autoscaling/v2beta2
      validate:
        message: >-
          {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.26.
          See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        deny: {}
    - name: validate-v1-27-removals
      match:
        any:
          - resources:
              kinds:
                - storage.k8s.io/*/CSIStorageCapacity
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
          - key: "{{request.object.apiVersion}}"
            operator: AnyIn
            value:
              - storage.k8s.io/v1beta1
      validate:
        message: >-
          {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.27.
          See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        deny: {}
    - name: validate-v1-29-removals
      match:
        any:
          - resources:
              kinds:
                - flowcontrol.apiserver.k8s.io/*/FlowSchema
                - flowcontrol.apiserver.k8s.io/*/PriorityLevelConfiguration
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
          - key: "{{request.object.apiVersion}}"
            operator: AnyIn
            value:
              - flowcontrol.apiserver.k8s.io/v1beta2
      validate:
        message: >-
          {{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.29.
          See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        deny: {}
