apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-empty-ingress-host
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: disallow-empty-ingress-host
      match:
        any:
          - resources:
              kinds:
                - Ingress
      validate:
        message: "The Ingress host name must be defined, not empty."
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.rules[].host || `[]` | length(@) }}"
                operator: NotEquals
                value: "{{ request.object.spec.rules[].http || `[]` | length(@) }}"
