apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-deprecated-registry
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-deprecated-registry
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: 'The "k8s.gcr.io" image registry is deprecated. "registry.k8s.io" should now be used.'
        foreach:
          - list: "request.object.spec.[initContainers, ephemeralContainers, containers][]"
            deny:
              conditions:
                all:
                  - key: "{{ element.image }}"
                    operator: Equals
                    value: "k8s.gcr.io/*"
