---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ../../../bases/cert-manager

patches:
  - path: version.yaml
    target:
      kind: HelmRelease
      name: cert-manager
