---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  labels:
    app.kubernetes.io/component: ingress
    toolkit.fluxcd.io/tenant: clusterops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: ingress
    toolkit.fluxcd.io/tenant: clusterops
  name: flux-${name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux
