controller:
  nodeSelector:
    kubernetes.io/os: linux
  service:
    type: NodePort
    nodePorts:
      http: 32001
      https: 32002
    ipFamilyPolicy: SingleStack
    externalTrafficPolicy: Local
