apiVersion: v1
kind: Namespace
metadata:
  name: internal-dns
  labels:
    app.kubernetes.io/component: dns
    toolkit.fluxcd.io/tenant: infra
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: internal-dns
  labels:
    app.kubernetes.io/component: dns
    toolkit.fluxcd.io/tenant: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: dns
    toolkit.fluxcd.io/tenant: infra
  name: flux-internal-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: internal-dns
