---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: victoria-metrics
spec:
  image: "ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: victoria-metrics
spec:
  imageRepositoryRef:
    name: victoria-metrics
  policy:
    semver:
      range: ">=0.0.0 <1.0.0"
