controller:
  nodeSelector:
    kubernetes.io/os: linux
  service:
    type: NodePort
    nodePorts:
      http: 31001
      https: 31002
    ipFamilyPolicy: SingleStack
    externalTrafficPolicy: Local
