apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../../bases/kube-prometheus-stack

patches:
  - path: version.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
  - patch: |
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 48h
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
