---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 12h
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "1.19.2" # {"$imagepolicy": "flux-system:cert-manager:tag"}
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
  values:
    crds:
      enabled: true
      keep: true
