---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admission.yaml
  - dns.yaml
  - ingress.yaml
  - ipam.yaml
  - monitoring.yaml
  - storage.yaml
  - tls.yaml

labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra
