---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-components
  namespace: flux-system
spec:
  serviceAccountName: flux-infra
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  path: deploy/${ENVIRONMENT}
