apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./victoria-metrics.yaml

configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - values.yaml=kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-vm-config
    files:
      - values.yaml=vm-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring

configurations:
  - kustomizeconfig.yaml
