apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/victoriametrics/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmks
spec:
  serviceAccountName: flux
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
    - kind: ConfigMap
      name: flux-vm-config
