---
global:
  clusterLabel: cluster

victoria-metrics-operator:
  enabled: true
  serviceMonitor:
    enabled: true

defaultDashboards:
  enabled: true
  defaultTimezone: ${TIMEZONE}

vmsingle:
  enabled: true

grafana:
  enabled: true

prometheus-node-exporter:
  service:
    port: 9022
    targetPort: metrics
  vmScrape:
    enabled: true

prometheus-operator-crds:
  enabled: true
