fullnameOverride: nginx-external
controller:
  extraEnvs:
    - name: TZ
      value: "${TIMEZONE}"
  service:
    type: NodePort
    nodePorts:
      http: 31000
      https: 32000
    externalIPs:
      - 216.66.68.16
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
    externalTrafficPolicy: Local
  publishService:
    enabled: true
  ingressClassResource:
    enabled: true
    name: nginx-external
    default: false
    controllerValue: cleroux.com/nginx-external
  ingressClass: nginx-external
  ingressClassByName: true

  config:
    client-header-timeout: 120
    client-body-buffer-size: "100M"
    client-body-timeout: 120
    enable-brotli: "true"
    hsts-max-age: "31449600"
    keep-alive: 120
    keep-alive-requests: 10000
    proxy-body-size: "100M"
    ssl-protocols: "TLSv1.3 TLSv1.2"
