---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-external
  labels:
    app.kubernetes.io/component: ingress
    toolkit.fluxcd.io/tenant: clusterops
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-external
  namespace: flux-system
spec:
  targetNamespace: ingress-nginx-external
  dependsOn:
    - name: metallb-config
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./components/networking/ingress-nginx/controller/base
  postBuild:
    substitute:
      name: nginx-external
      domain: cleroux.com
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
