---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ks.yaml

configMapGenerator:
  - name: service-config
    namespace: ingress-nginx-external
    files:
      - service-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: ingress

configurations:
  - kustomizeconfig.yaml
