apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../../bases/victoria-metrics

patches:
  - path: version.yaml
    target:
      kind: HelmRelease
      name: vmks
  - path: valuesFrom.yaml
    target:
      kind: HelmRelease
      name: vmks

configMapGenerator:
  - name: flux-vm-ingress-config
    files:
      - values.yaml=./vm-ingress.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring

configurations:
  - kustomizeconfig.yaml
