apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
spec:
  targetNamespace: monitoring
  interval: 1m
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus-stack
  path: components/monitoring/kube-prometheus-stack/controller/base
  postBuild:
    substitute:
      version: "66.2.1" # {"$imagepolicy": "monitoring:kube-prometheus-stack:tag"}
