---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
  - ../../../bases/openebs

patches:
  - path: ./version.yaml
    target:
      kind: HelmRelease
  - path: ./valuesFrom.yaml
    target:
      kind: HelmRelease

configMapGenerator:
  - name: flux-openebs-config
    files:
      - values.yaml=openebs-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        toolkit.fluxcd.io/tenant: infra
        app.kubernetes.io/component: storage

configurations:
  - kustomizeconfig.yaml
