---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ks.yaml
  - ./source.yaml
  - ./update.yaml

secretGenerator:
  - name: source-git
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    envs:
      - ./git.env
