---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
spec:
  interval: 1m0s
  url: https://github.com/cleroux-dev-homelab/flux-infra.git
  ref:
    branch: main
  secretRef:
    name: source-git
  ignore: |
    /*
    !/components/monitoring/metrics-server
