---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/role: automation
spec:
  image: "ghcr.io/cloudnative-pg/charts/cloudnative-pg"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cloudnative-pg
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/role: automation
spec:
  imageRepositoryRef:
    name: cloudnative-pg
  policy:
    semver:
      range: ">=0.23.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: cloudnative-pg
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/role: automation
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-infra
  git:
    checkout:
      ref:
        branch: main
    commit:
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
      author:
        email: fluxcdbot@noreply.cleroux.dev
        name: fluxcdbot
    push:
      branch: main
  update:
    path: "./components/database/controllers/postgres"
    strategy: Setters
