apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../../bases/metrics-server

patches:
  - path: version.yaml
    target:
      kind: HelmRelease
      name: metrics-server
