---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
spec:
  interval: 12h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  serviceAccountName: flux
  interval: 1h
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
