---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: k8s-gateway
spec:
  image: "ghcr.io/pinax-network/charts/k8s-gateway"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: k8s-gateway
spec:
  imageRepositoryRef:
    name: k8s-gateway
  policy:
    semver:
      range: ">=3.0.0"
