---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ks.yaml

configMapGenerator:
  - name: flux-ingress-nginx-config
    namespace: ingress-nginx-internal
    files:
      - config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: ingress
