apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/component: database
    toolkit.fluxcd.io/tenant: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: database
    toolkit.fluxcd.io/tenant: infra
  name: flux-cnpg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: cnpg-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: cnpg-system
  labels:
    app.kubernetes.io/component: database
    toolkit.fluxcd.io/tenant: infra
