---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-controller
  namespace: flux-system
spec:
  targetNamespace: monitoring
  dependsOn:
    - name: ingress-nginx-controller
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./components/monitoring/kube-prometheus-stack/controller/envs/${ENVIRONMENT}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-config
  namespace: flux-system
spec:
  targetNamespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack-controller
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./components/monitoring/kube-prometheus-stack/config/envs/${ENVIRONMENT}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
