fullnameOverride: internal-dns
domain: "${CLUSTER_NAME}.${INTERNAL_DOMAIN}"
ttl: 30
watchedResources:
  - Ingress
debug:
  enabled: true
service:
  type: NodePort
  nodePort: 32000
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack

dnsChallenge:
  k8s_gateway:
    enabled: true

# Optional plugins that will be enabled in the zone, e.g. "forward . /etc/resolve.conf"
extraZonePlugins:
  - name: log
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: forward
    parameters: . /etc/resolv.conf
  - name: loop
  - name: reload
  - name: loadbalance
