---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-dns

resources:
  - ../../../bases/k8s_gateway

patches:
  - path: version.yaml
    target:
      kind: HelmRelease

  - path: values.yaml
    target:
      kind: HelmRelease

configMapGenerator:
  # Creating an empty cm here to patch in components
  - name: flux-k8s-gateway-config
    files:
      - values.yaml=./gateway-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: dns

configurations:
  - kustomizeconfig.yaml
