---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/cloudnative-pg/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.27.0" # {"$imagepolicy": "flux-system:cloudnative-pg:tag"}
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
