---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: webhook-pinax
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/pinax-network/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webhook-pinax
spec:
  dependsOn:
    - name: cert-manager
  serviceAccountName: flux
  interval: 1h
  chart:
    spec:
      chart: cert-manager-webhook-pinax
      sourceRef:
        kind: HelmRepository
        name: webhook-pinax
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
