apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager.yaml
  - ./cert-manager-webhook-pinax.yaml

configMapGenerator:
  - name: flux-cert-manager-config
    files:
      - values.yaml=cert-manager-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: tls

configurations:
  - kustomizeconfig.yaml
