---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 12h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
