apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-external

resources:
  - ../../../bases/ingress-nginx

patches:
  - path: values.yaml
    target:
      kind: HelmRelease

  - path: valuesFrom.yaml
    target:
      kind: HelmRelease

  - path: version.yaml
    target:
      kind: HelmRelease

configMapGenerator:
  - name: nginx-service-config
    files:
      - values.yaml=service-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: ingress

configurations:
  - kustomizeconfig.yaml
