controller:
  nodeSelector:
    kubernetes.io/os: linux
  service:
    type: NodePort
    nodePorts:
      http: 31003
      https: 31004
    ipFamilyPolicy: SingleStack
    externalTrafficPolicy: Local
