apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
  values:
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    args:
      - --kubelet-insecure-tls
